// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBo-HIZmlx12SLXA2djJteA014ggAJgYk',
    appId: '1:68721212611:web:4229d142c14edcb5e5b676',
    messagingSenderId: '68721212611',
    projectId: 'adhicine-c828f',
    authDomain: 'adhicine-c828f.firebaseapp.com',
    storageBucket: 'adhicine-c828f.appspot.com',
    measurementId: 'G-WPV704CYMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlGHQrvOObxe7jeiu2ia0HfKNhOtMWIU',
    appId: '1:68721212611:android:26a8e16be8e3cd67e5b676',
    messagingSenderId: '68721212611',
    projectId: 'adhicine-c828f',
    storageBucket: 'adhicine-c828f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM27gHbBwabp_HTecZNUwincM-XUwecD8',
    appId: '1:68721212611:ios:8814605b6abca072e5b676',
    messagingSenderId: '68721212611',
    projectId: 'adhicine-c828f',
    storageBucket: 'adhicine-c828f.appspot.com',
    iosClientId: '68721212611-bfs500sor6djt3q1hcu3rl7bl64r3vk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.adhicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM27gHbBwabp_HTecZNUwincM-XUwecD8',
    appId: '1:68721212611:ios:8814605b6abca072e5b676',
    messagingSenderId: '68721212611',
    projectId: 'adhicine-c828f',
    storageBucket: 'adhicine-c828f.appspot.com',
    iosClientId: '68721212611-bfs500sor6djt3q1hcu3rl7bl64r3vk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.adhicine',
  );
}
